-- =====================================================
-- Database Schema Creation for Testing Environment
-- Generated from Hibernate DDL output
-- =====================================================

-- Create domain table
CREATE TABLE domain (
    domain_id integer generated by default as identity,
    name varchar(100) not null,
    primary key (domain_id)
);

-- Create roles table
CREATE TABLE roles (
    id bigint generated by default as identity,
    name varchar(255) not null unique,
    primary key (id)
);

-- Create users table
CREATE TABLE users (
    is_email_verified BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    role_id bigint not null,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    id uuid not null,
    email varchar(255) not null unique,
    name varchar(255),
    password varchar(255),
    providerid varchar(255) unique,
    primary key (id)
);

-- Create tutor table
CREATE TABLE tutor (
    dob date,
    last_accessed date,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tutor_id uuid not null,
    address varchar(255) not null,
    bio TEXT,
    city varchar(255) not null,
    country varchar(255) not null,
    first_name varchar(255) not null,
    gender varchar(255) not null check (gender in ('MALE','FEMALE','OTHER')),
    image TEXT,
    last_name varchar(255) not null,
    phone_no varchar(255) not null unique,
    portfolio TEXT,
    status varchar(255) check (status in ('PENDING','APPROVED','BANNED')),
    primary key (tutor_id)
);

-- Create student table
CREATE TABLE student (
    birthday date,
    is_active boolean,
    last_accessed date,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    student_id uuid not null,
    address varchar(255) not null,
    bio TEXT,
    city varchar(255) not null,
    country varchar(255) not null,
    first_name varchar(255) not null,
    image_url varchar(255),
    last_name varchar(255) not null,
    phone_number varchar(255) not null unique,
    primary key (student_id)
);

-- Create modules table
CREATE TABLE modules (
    average_ratings numeric(3,1),
    domain integer,
    duration numeric(21,0),
    fee numeric(10,2) not null,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    module_id uuid not null,
    tutor_id uuid not null,
    status varchar(20) check (status in ('Draft','Active','Archived')),
    name varchar(255) not null,
    primary key (module_id)
);

-- Create recurrent table
CREATE TABLE recurrent (
    recurrent_id integer generated by default as identity,
    recurrent_type varchar(50) not null,
    primary key (recurrent_id)
);

-- Create schedules table
CREATE TABLE schedules (
    date date not null,
    duration integer not null,
    recurrent_id integer,
    time time(6) not null,
    week_number integer,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    module_id uuid not null,
    schedule_id uuid not null,
    primary key (schedule_id)
);

-- Create enrollment table
CREATE TABLE enrollment (
    is_paid boolean not null,
    enrolment_id uuid not null,
    module_id uuid not null,
    student_id uuid not null,
    primary key (enrolment_id),
    unique (student_id, module_id)
);

-- Create material table
CREATE TABLE material (
    material_id uuid not null,
    module_id uuid,
    description varchar(255) not null,
    title varchar(255) not null,
    type varchar(255) not null,
    url varchar(255) not null,
    primary key (material_id)
);

-- Create payments table
CREATE TABLE payments (
    amount FLOAT8 not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    currency varchar(10) not null,
    module_id uuid not null,
    payment_id uuid not null,
    student_id uuid not null,
    order_id varchar(255) not null unique,
    payhere_payment_id varchar(255),
    payhere_signature varchar(255),
    status varchar(255) not null,
    primary key (payment_id)
);

-- Create rating table
CREATE TABLE rating (
    rating numeric(2,1),
    created_at timestamp(6) with time zone not null,
    enrolment_id uuid not null,
    module_id uuid not null,
    feedback TEXT,
    student_name varchar(255),
    primary key (enrolment_id)
);

-- Create notification_tracking table
CREATE TABLE notification_tracking (
    scheduled_date date not null,
    scheduled_time time(6) not null,
    created_at timestamp(6) with time zone not null,
    notification_fired_at timestamp(6) with time zone not null,
    id uuid not null,
    schedule_id uuid not null,
    primary key (id),
    unique (schedule_id, scheduled_date, scheduled_time)
);

-- Create wallet table
CREATE TABLE wallet (
    tutor_id uuid not null,
    available_balance FLOAT8 not null,
    updated_at timestamp(6) with time zone,
    primary key (tutor_id)
);

-- Create withdrawals table
CREATE TABLE withdrawals (
    withdrawal_id uuid not null,
    tutor_id uuid not null,
    tutor_name varchar(255) not null,
    amount FLOAT8 not null,
    status varchar(255) not null,
    method varchar(255) not null,
    account_name varchar(255) not null,
    bank_name varchar(255),
    account_number varchar(255) not null,
    notes TEXT,
    created_at timestamp(6) with time zone not null,
    processed_at timestamp(6) with time zone,
    admin_id uuid,
    transaction_id varchar(255),
    paid_at timestamp(6) with time zone,
    primary key (withdrawal_id)
);

-- Add foreign key constraints
ALTER TABLE users ADD CONSTRAINT FKp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES roles;
ALTER TABLE tutor ADD CONSTRAINT FKd1fg4ojpgb32brt8wat35o7ji FOREIGN KEY (tutor_id) REFERENCES users;
ALTER TABLE student ADD CONSTRAINT FKbjuuwdqnx5y9nmn38223wokev FOREIGN KEY (student_id) REFERENCES users;
ALTER TABLE modules ADD CONSTRAINT FKjmiepf1usrw4u7pmdx9qv8fay FOREIGN KEY (domain) REFERENCES domain;
ALTER TABLE modules ADD CONSTRAINT FK5j79ysm5ll8bb5gbrys3hb9e6 FOREIGN KEY (tutor_id) REFERENCES tutor;
ALTER TABLE schedules ADD CONSTRAINT FK3vh9t5samttx20l2i541uhw77 FOREIGN KEY (module_id) REFERENCES modules;
ALTER TABLE schedules ADD CONSTRAINT FKt86ylnyj3tl8vmioy9a2hut6y FOREIGN KEY (recurrent_id) REFERENCES recurrent;
ALTER TABLE enrollment ADD CONSTRAINT FKku7hb2qg5l2q9b99kx2sqc2k7 FOREIGN KEY (module_id) REFERENCES modules;
ALTER TABLE enrollment ADD CONSTRAINT FKio7fsy3vhvfgv7c0gjk15nyk4 FOREIGN KEY (student_id) REFERENCES student;
ALTER TABLE material ADD CONSTRAINT FK7epcyukx805hbitlsp5httga4 FOREIGN KEY (module_id) REFERENCES modules;
ALTER TABLE payments ADD CONSTRAINT FK5r1n1of8jsigg0xxfvvq11odw FOREIGN KEY (module_id) REFERENCES modules;
ALTER TABLE payments ADD CONSTRAINT FKo0lgt74t3bsgmnfq54pcdew7y FOREIGN KEY (student_id) REFERENCES student;
ALTER TABLE rating ADD CONSTRAINT FK1bfp8op46vayyf5yw015ipbm2 FOREIGN KEY (enrolment_id) REFERENCES enrollment;
ALTER TABLE wallet ADD CONSTRAINT FKwallet_tutor_id FOREIGN KEY (tutor_id) REFERENCES tutor;
ALTER TABLE withdrawals ADD CONSTRAINT FKwithdrawals_tutor_id FOREIGN KEY (tutor_id) REFERENCES tutor;
ALTER TABLE withdrawals ADD CONSTRAINT FKwithdrawals_admin_id FOREIGN KEY (admin_id) REFERENCES users;