-- Create module_description table
CREATE TABLE module_description (
    id bigint generated by default as identity,
    module_id uuid,
    name varchar(255) not null default 'Sample Module',
    domain varchar(255) not null default 'Sample Domain',
    price integer not null default 0,
    tutor_name varchar(255) not null default 'MR.X',
    description TEXT not null default 'No description available',
    primary key (id)
);